syntax = "proto3";

package ru.my.scents.grpc.fragrance;

option java_multiple_files = true;
option java_package = "ru.my.scents.fragrance.adapter.controller.grpc.fragrance.proto";

import "google/protobuf/timestamp.proto";
import "fragrance/fragrance_availability_status.proto";
import "fragrance/fragrance_gender.proto";
import "fragrance/fragrance_longevity.proto";
import "fragrance/fragrance_sillage.proto";
import "fragrance/fragrance_season.proto";
import "fragrance/fragrance_type.proto";
import "fragrance/fragrance_concentration.proto";

message FragranceData {
  string id = 1;
  string name = 2;
  string resume = 3;
  int32 rating = 4;
  FragranceConcentration concentration = 5;
  repeated FragranceType type = 6;
  FragranceGender gender = 7;
  repeated FragranceSeason season = 8;
  FragranceLongevity longevity = 9;
  FragranceSillage sillage = 10;
  FragranceAvailabilityStatus availability = 11;
  google.protobuf.Timestamp created_at = 12;
  google.protobuf.Timestamp updated_at = 13;
}