server:
  port: 8087
  jetty:
    connection-idle-timeout: 60000
    max-connections: 200
    threads:
      min: 8
      max: 200
      idle-timeout: 60000
  shutdown: graceful

management:
  server:
    port: 8086
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus, health, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: my-scents
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

spring:
  application:
    name: my-scents
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/myscentsdb?authSource=admin
  lifecycle:
    timeout-per-shutdown-phase: 60s
  grpc:
    server:
      servlet:
        enabled: false
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100

kafka:
  retry:
    attempts: 4
    initial-interval-ms: 10000
    max-interval-ms: 60000
    multiplier: 2.0
  topics:
    my-scents-fragrance:
      name: my-scents-fragrance-events
      concurrency: 1
      auto-create-topics: true
      replication-factor: 1
      num-partitions: 1
    my-scents-fragrance-dlt:
      name: my-scents-fragrance-events-dlt
      concurrency: 1
      auto-create-topics: true
      replication-factor: 1
      num-partitions: 1
    outer-fragrance:
      name: outer-fragrance-events
      concurrency: 1
      auto-create-topics: true
      replication-factor: 1
      num-partitions: 1
    outer-fragrance-dlt:
      name: outer-fragrance-events-dlt
      concurrency: 1
      auto-create-topics: true
      replication-factor: 1
      num-partitions: 1

logging:
  queue:
    capacity: 100
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    ru.my.scents: DEBUG

grpc:
  server:
    port: 50053
    shutdown-grace-period: 30s
  fragrance-service:
    host: localhost
    port: 50051
    deadline: 60s
    retry:
      max-attempts: 10
      initial-backoff: 5000ms
      max-backoff: 10000ms
      multiplier: 1.5
      per-attempt-timeout: 10000ms
      thread-pool-size: 1