server:
  port: 8081
  jetty:
    connection-idle-timeout: 60000
    max-connections: 200
    threads:
      min: 8
      max: 200
      idle-timeout: 60000

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus, health, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: my-scents
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

spring:
  application:
    name: my-scents
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none

logging:
  queue:
    capacity: 100